import { Box, Container, Flex, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import LoginButton from "../components/LoginButton";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jiffy Bag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="md" padding={"1rem"} height="100vh">
        <Box>
          <Heading textAlign={"center"}>Jiffy Bag</Heading>
        </Box>

        <Heading textAlign={"center"} as="h2" fontSize={"xl"}>
          {"Genz's go to app for Personal Finance"}
        </Heading>

        <Flex alignItems="center" justifyContent="center" padding={4}>
          <LoginButton />
        </Flex>
      </Container>
    </div>
  );
}
